# Generated by Django 3.1.2 on 2020-10-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
